---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# unhcrthemes

<!-- badges: start -->
<!-- badges: end -->

The goal of unhcrthemes is to provide a collection of template, palettes and themes for plots, documents, and slides based on UNHCR branding.

## Installation

You can install the released version of unhcrthemes from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("unhcrthemes")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("vidonne/unhcrthemes")
```
## Usage

```{r loading, message=FALSE, warning=FALSE, error=FALSE}
library(unhcrthemes)
library(ggplot2)
```

### Base ggplot2 theme

```{r plot-theme}
ggplot(datasets::iris, aes(x = Petal.Length, y = Petal.Width)) +
  geom_point() +
  labs(x="Petal length", y="Petal width",
      title = "Iris data ggplot2 scatterplot example",
      subtitle= "Just a simple plot to show the basic style of theme_unhcr",
      caption = "Data from datasets::iris") +
  theme_unhcr()
```

