library(colorspace)
library(usethis)

main_blue <- "#0072BC"
main_darkblue <- "#18375F"
main_green <- "#00B398"
main_red <- "#EF4A60"
main_grey <- colorspace::lighten("black", 0.4)
main_yellow <- "#FAEB00"
alt_yellow <- "#BB9D21"

pal_blue_unhcr <- c(
  "blue5" = colorspace::darken(main_blue, 0.3),
  "blue4" = main_blue,
  "blue3" = colorspace::lighten(main_blue, 0.3),
  "blue2" = colorspace::lighten(main_blue, 0.6),
  "blue1" = colorspace::lighten(main_blue, 0.85)
)

pal_darkblue_unhcr <- c(
  "darkblue5" = main_darkblue,
  "darkblue4" = colorspace::lighten(main_darkblue, 0.25),
  "darkblue3" = colorspace::lighten(main_darkblue, 0.5),
  "darkblue2" = colorspace::lighten(main_darkblue, 0.75),
  "darkblue1" = colorspace::lighten(main_darkblue, 0.9)
)

pal_green_unhcr <- c(
  "green5" = colorspace::darken(main_green, 0.3),
  "green4" = main_green,
  "green3" = colorspace::lighten(main_green, 0.3),
  "green2" = colorspace::lighten(main_green, 0.6),
  "green1" = colorspace::lighten(main_green, 0.9)
)

pal_red_unhcr <- c(
  "red5" = colorspace::darken(main_red, 0.3),
  "red4" = main_red,
  "red3" = colorspace::lighten(main_red, 0.3),
  "red2" = colorspace::lighten(main_red, 0.6),
  "red1" = colorspace::lighten(main_red, 0.85)
)

pal_grey_unhcr <- c(
  "grey5" = colorspace::lighten("black", 0.2),
  "grey4" = main_grey,
  "grey3" = colorspace::lighten("black", 0.6),
  "grey2" = colorspace::lighten("black", 0.8),
  "grey1" = colorspace::lighten("black", 0.9)
)

pal_yellow_unhcr <- c(
  "yellow5" = alt_yellow,
  "yellow4" = hex(colorspace::mixcolor(0.4,
                                       hex2RGB(main_yellow),
                                       hex2RGB(alt_yellow))),
  "yellow3" = main_yellow,
  "yellow2" = colorspace::lighten(main_yellow, 0.4),
  "yellow1" = colorspace::lighten(main_yellow, 0.7)
)

pal_main_unhcr <- c(main_blue,
                    main_darkblue,
                    main_green,
                    main_grey,
                    main_red)

pal_pair_unhcr <- c(main_blue, pal_blue_unhcr["blue2"],
                    main_darkblue, pal_darkblue_unhcr["darkblue3"],
                    main_green, pal_green_unhcr["green2"],
                    main_grey, pal_grey_unhcr["grey2"],
                    main_red, pal_red_unhcr["red2"])


pal_blue_red_d <- c(pal_blue_unhcr[2],
                    pal_blue_unhcr[3],
                    pal_blue_unhcr[4],
                    pal_grey_unhcr[5],
                    pal_red_unhcr[4],
                    pal_red_unhcr[3],
                    pal_red_unhcr[2])


pal_darkblue_red_d <- c(pal_darkblue_unhcr[1],
                        pal_darkblue_unhcr[2],
                        pal_darkblue_unhcr[3],
                        pal_grey_unhcr[5],
                        pal_red_unhcr[4],
                        pal_red_unhcr[3],
                        pal_red_unhcr[2])

pal_darkblue_yellow_d <- c(pal_darkblue_unhcr[1],
                           pal_darkblue_unhcr[2],
                           pal_darkblue_unhcr[3],
                           pal_grey_unhcr[5],
                           pal_yellow_unhcr[4],
                           pal_yellow_unhcr[3],
                           pal_yellow_unhcr[2])

unhcrcolors <- tibble::tibble(name = c("pal_main_qual",
                                       "pal_pair_qual",
                                       "pal_blue_seq",
                                       "pal_darkblue_seq",
                                       "pal_green_seq",
                                       "pal_red_seq",
                                       "pal_yellow_seq",
                                       "pal_grey_seq",
                                       "pal_blue_red_div",
                                       "pal_darkblue_red_div",
                                       "pal_darkblue_yellow_div"),
                              type = c(rep("qualitative", 2),
                                       rep("sequential", 6),
                                       rep("diverging", 3)),
                              min_n = 2,
                              max_n = c(c(5, 10),
                                        rep(5, 6),
                                        rep(7,  3)),
                              n2 = list(pal_main_unhcr[1:2],
                                        pal_pair_unhcr[1:2],
                                        c(main_blue,
                                          pal_blue_unhcr["blue2"]),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"]),
                                        c(main_green,
                                          pal_green_unhcr["green2"]),
                                        c(main_red,
                                          pal_red_unhcr["red2"]),
                                        c(pal_yellow_unhcr["yellow4"],
                                          main_yellow),
                                        c(main_grey,
                                          pal_grey_unhcr["grey2"]),
                                        c(main_blue,
                                          main_red),
                                        c(main_darkblue,
                                          main_red),
                                        c(main_darkblue,
                                          pal_yellow_unhcr["yellow4"])),
                              n3 = list(pal_main_unhcr[1:3],
                                        pal_pair_unhcr[1:3],
                                        c(main_blue,
                                          pal_blue_unhcr["blue3"],
                                          pal_blue_unhcr["blue2"]),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_darkblue_unhcr["darkblue2"]),
                                        c(main_green,
                                          pal_green_unhcr["green3"],
                                          pal_green_unhcr["green2"]),
                                        c(main_red,
                                          pal_red_unhcr["red3"],
                                          pal_red_unhcr["red2"]),
                                        c(pal_yellow_unhcr["yellow4"],
                                          main_yellow,
                                          pal_yellow_unhcr["yellow1"]),
                                        c(main_grey,
                                          pal_grey_unhcr["grey3"],
                                          pal_grey_unhcr["grey2"]),
                                        c(main_blue,
                                          pal_grey_unhcr["grey1"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_grey_unhcr["grey1"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_grey_unhcr["grey1"],
                                          pal_yellow_unhcr["yellow4"])),
                              n4 = list(pal_main_unhcr[1:4],
                                        pal_pair_unhcr[1:4],
                                        c(main_blue,
                                          pal_blue_unhcr["blue3"],
                                          pal_blue_unhcr["blue2"],
                                          pal_blue_unhcr["blue1"]),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue4"],
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_darkblue_unhcr["darkblue2"]),
                                        c(main_green,
                                          pal_green_unhcr["green3"],
                                          pal_green_unhcr["green2"],
                                          pal_green_unhcr["green1"]),
                                        c(main_red,
                                          pal_red_unhcr["red3"],
                                          pal_red_unhcr["red2"],
                                          pal_red_unhcr["red1"]),
                                        c(pal_yellow_unhcr["yellow4"],
                                          main_yellow,
                                          pal_yellow_unhcr["yellow2"],
                                          pal_yellow_unhcr["yellow1"]),
                                        c(main_grey,
                                          pal_grey_unhcr["grey3"],
                                          pal_grey_unhcr["grey2"],
                                          pal_grey_unhcr["grey1"]),
                                        c(main_blue,
                                          pal_blue_unhcr["blue3"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          main_yellow,
                                          pal_yellow_unhcr["yellow4"])),
                              n5 = list(pal_main_unhcr,
                                        pal_pair_unhcr[1:5],
                                        pal_blue_unhcr,
                                        pal_darkblue_unhcr,
                                        pal_green_unhcr,
                                        pal_red_unhcr,
                                        pal_yellow_unhcr,
                                        pal_grey_unhcr,
                                        c(main_blue,
                                          pal_blue_unhcr["blue3"],
                                          pal_grey_unhcr["grey1"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_grey_unhcr["grey1"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_grey_unhcr["grey1"],
                                          main_yellow,
                                          pal_yellow_unhcr["yellow4"])),
                              n6 = list(NULL,
                                        pal_pair_unhcr[1:6],
                                        NULL, NULL, NULL,
                                        NULL, NULL, NULL,
                                        c(main_blue,
                                          pal_blue_unhcr["blue3"],
                                          pal_blue_unhcr["blue2"],
                                          pal_red_unhcr["red2"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_darkblue_unhcr["darkblue2"],
                                          pal_red_unhcr["red2"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_darkblue_unhcr["darkblue2"],
                                          pal_yellow_unhcr["yellow2"],
                                          main_yellow,
                                          pal_yellow_unhcr["yellow4"])),
                              n7 = list(NULL,
                                        pal_pair_unhcr[1:7],
                                        NULL, NULL, NULL,
                                        NULL, NULL, NULL,
                                        c(main_blue,
                                          pal_blue_unhcr["blue3"],
                                          pal_blue_unhcr["blue2"],
                                          pal_grey_unhcr["grey1"],
                                          pal_red_unhcr["red2"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_darkblue_unhcr["darkblue2"],
                                          pal_grey_unhcr["grey1"],
                                          pal_red_unhcr["red2"],
                                          pal_red_unhcr["red3"],
                                          main_red),
                                        c(main_darkblue,
                                          pal_darkblue_unhcr["darkblue3"],
                                          pal_darkblue_unhcr["darkblue2"],
                                          pal_grey_unhcr["grey1"],
                                          pal_yellow_unhcr["yellow2"],
                                          pal_yellow_unhcr["yellow3"],
                                          main_yellow)),
                              n8 = list(NULL,
                                        pal_pair_unhcr[1:8],
                                        NULL, NULL, NULL,
                                        NULL, NULL,
                                        NULL, NULL,
                                        NULL, NULL),
                              n9 = list(NULL,
                                        pal_pair_unhcr[1:9],
                                        NULL, NULL, NULL,
                                        NULL, NULL,
                                        NULL, NULL,
                                        NULL, NULL),
                              n10 = list(NULL,
                                         pal_pair_unhcr,
                                         NULL, NULL, NULL,
                                         NULL, NULL,
                                         NULL, NULL,
                                         NULL, NULL))


unhcrcolors <- as.data.frame(unhcrcolors)

usethis::use_data(unhcrcolors,
                  internal = TRUE,
                  overwrite = TRUE)
