unhcrcolors <- data.frame(name = c("pal_blue_s",
                                       "pal_darkblue_s",
                                       "pal_green_s",
                                       "pal_red_s",
                                       "pal_yellow_s",
                                       "pal_grey_s",
                                       "pal_main_c",
                                       "pal_shade_c",
                                       "pal_blue_red_d",
                                       "pal_darkblue_red_d",
                                       "pal_darkblue_yellow_d"),
                              type = c(rep("sequential", 6),
                                       rep("qualitative", 2),
                                       rep("diverging", 3)),
                              min_n = 2,
                              max_n = c(rep(5, 6),
                                        c(5, 10),
                                        rep(7,  3)),
                              n2 = list(c("#044F85", "#0072BC"),
                                        c("#18375F", "#506489"),
                                        c("#027B68", "#00B398"),
                                        c("#B41C37", "#EF4A60"),
                                        c("#BB9D21", "#E1CC0D"),
                                        c("#303030", "#5E5E5E"),
                                        c("#0072BC", "#EF4A60"),
                                        c("#0072BC", "#EF4A60"),
                                        c("#0072BC", "#EF4A60"),
                                        c("#18375F", "#EF4A60"),
                                        c("#18375F", "#E1CC0D")),
                              n3 = list(c("#044F85", "#0072BC", "#589BE5"),
                                        c("#18375F", "#506489", "#8395B9"),
                                        c("#027B68", "#00B398", "#49CFB4"),
                                        c("#B41C37", "#EF4A60", "#FF8490"),
                                        c("#BB9D21", "#E1CC0D", "#FAEB00"),
                                        c("#303030", "#5E5E5E", "#919191"),
                                        c("#0072BC", "#00B398", "#EF4A60"),
                                        c("#0072BC", "#70ECD1", "#EF4A60"),
                                        c("#0072BC", "#E2E2E2", "#EF4A60"),
                                        c("#18375F", "#E2E2E2", "#EF4A60"),
                                        c("#18375F", "#E2E2E2", "#E1CC0D")),
                              n4 = list(c("#044F85", "#0072BC", "#589BE5",
                                          "#9DC5FF"),
                                        c("#18375F", "#506489", "#8395B9",
                                          "#B8C9EE"),
                                        c("#027B68", "#00B398", "#49CFB4",
                                          "#70ECD1"),
                                        c("#B41C37", "#EF4A60", "#FF8490",
                                          "#FFBCC1"),
                                        c("#BB9D21", "#E1CC0D", "#FAEB00",
                                          "#FFF483"),
                                        c("#303030", "#5E5E5E", "#919191",
                                          "#C6C6C6"),
                                        c("#0072BC", "#00B398", "#5E5E5E",
                                          "#EF4A60"),
                                        c("#0072BC", "#70ECD1", "#EF4A60",
                                          "#FFBCC1"),
                                        c("#0072BC", "#9DC5FF", "#E2E2E2",
                                          "#EF4A60"),
                                        c("#18375F", "#8395B9", "#E2E2E2",
                                          "#EF4A60"),
                                        c("#18375F", "#8395B9", "#E2E2E2",
                                          "#E1CC0D")),
                              n5 = list(c("#044F85", "#0072BC", "#589BE5",
                                          "#9DC5FF", "#DCE9FF"),
                                        c("#18375F", "#506489", "#8395B9",
                                          "#B8C9EE", "#E0E9FE"),
                                        c("#027B68", "#00B398", "#49CFB4",
                                          "#70ECD1", "#CFFFF2"),
                                        c("#B41C37", "#EF4A60", "#FF8490",
                                          "#FFBCC1", "#FFE7E8"),
                                        c("#BB9D21", "#E1CC0D", "#FAEB00",
                                          "#FFF483", "#FFF9CB"),
                                        c("#303030", "#5E5E5E", "#919191",
                                          "#C6C6C6", "#E2E2E2"),
                                        c("#0072BC", "#18375F", "#00B398",
                                          "#5E5E5E", "#EF4A60"),
                                        c("#0072BC", "#18375F", "#70ECD1",
                                          "#EF4A60", "#FFBCC1"),
                                        c("#0072BC", "#9DC5FF", "#E2E2E2",
                                          "#FFBCC1", "#EF4A60"),
                                        c("#18375F", "#8395B9", "#E2E2E2",
                                          "#FFBCC1", "#EF4A60"),
                                        c("#18375F", "#8395B9", "#E2E2E2",
                                          "#FFF483", "#E1CC0D")),
                              n6 = list(NULL, NULL, NULL, NULL, NULL,
                                        NULL, NULL,
                                        c("#0072BC", "#9DC5FF", "#18375F",
                                          "#70ECD1", "#EF4A60", "#FFBCC1"),
                                        c("#0072BC", "#589BE5", "#9DC5FF",
                                          "#E2E2E2", "#FFBCC1", "#EF4A60"),
                                        c("#18375F", "#506489", "#8395B9",
                                          "#E2E2E2", "#FFBCC1", "#EF4A60"),
                                        c("#18375F", "#506489", "#8395B9",
                                          "#E2E2E2", "#FFF483", "#E1CC0D")),
                              n7 = list(NULL, NULL, NULL, NULL, NULL,
                                        NULL, NULL,
                                        c("#0072BC", "#9DC5FF", "#18375F",
                                          "#8395B9", "#70ECD1", "#EF4A60",
                                          "#FFBCC1"),
                                        c("#0072BC", "#589BE5", "#9DC5FF",
                                          "#E2E2E2", "#FFBCC1", "#FF8490",
                                          "#EF4A60"),
                                        c("#18375F", "#506489", "#8395B9",
                                          "#E2E2E2", "#FFBCC1", "#FF8490",
                                          "#EF4A60"),
                                        c("#18375F", "#506489", "#8395B9",
                                          "#E2E2E2", "#FFF483", "#FAEB00",
                                          "#E1CC0D")),
                              n8 = list(NULL, NULL, NULL, NULL, NULL,
                                        NULL, NULL,
                                        c("#0072BC", "#9DC5FF", "#18375F",
                                          "#8395B9", "#00B398", "#70ECD1",
                                          "#EF4A60", "#FFBCC1"),
                                        NULL, NULL, NULL),
                              n9 = list(NULL, NULL, NULL, NULL, NULL,
                                        NULL, NULL,
                                        c("#0072BC", "#9DC5FF", "#18375F",
                                          "#8395B9", "#00B398", "#70ECD1",
                                          "#5E5E5E",  "#EF4A60", "#FFBCC1"),
                                        NULL, NULL, NULL),
                              n10 = list(NULL, NULL, NULL, NULL, NULL,
                                         NULL, NULL,
                                         c("#0072BC", "#9DC5FF", "#18375F",
                                           "#8395B9", "#00B398", "#70ECD1",
                                           "#5E5E5E",  "#C6C6C6", "#EF4A60",
                                           "#FFBCC1"),
                                         NULL, NULL, NULL))
usethis::use_data(unhcrcolors,
                  internal = FALSE,
                  overwrite = TRUE)
